name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install SSH key
      run: |
        echo "${{ secrets.ecommerce }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      env:
        SSH_PRIVATE_KEY: ${{ secrets.commerce }}

    - name: SSH into EC2 and deploy
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@34.226.245.202 "cd /home/ubuntu/bot-dist && git pull && npm install && npm run build && sudo service nginx restart"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.commerce }}
